spring.application.name=demo-swaga
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=postgres
spring.datasource.password=ttGssaw@21
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/lesson-three.yml

student.avatar.dir.path=./avatars
